# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from weni.protobuf.wpp_router import channel_pb2 as weni_dot_protobuf_dot_wpp__router_dot_channel__pb2


class ChannelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateChannel = channel.unary_unary(
                '/weni.ai.whatsapp_router.ChannelService/CreateChannel',
                request_serializer=weni_dot_protobuf_dot_wpp__router_dot_channel__pb2.ChannelRequest.SerializeToString,
                response_deserializer=weni_dot_protobuf_dot_wpp__router_dot_channel__pb2.ChannelResponse.FromString,
                )


class ChannelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChannelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChannel,
                    request_deserializer=weni_dot_protobuf_dot_wpp__router_dot_channel__pb2.ChannelRequest.FromString,
                    response_serializer=weni_dot_protobuf_dot_wpp__router_dot_channel__pb2.ChannelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weni.ai.whatsapp_router.ChannelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChannelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/weni.ai.whatsapp_router.ChannelService/CreateChannel',
            weni_dot_protobuf_dot_wpp__router_dot_channel__pb2.ChannelRequest.SerializeToString,
            weni_dot_protobuf_dot_wpp__router_dot_channel__pb2.ChannelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
