# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from weni.protobuf.flows import channel_pb2 as weni_dot_protobuf_dot_flows_dot_channel__pb2


class ChannelControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/weni.flows.channel.ChannelController/Create',
                request_serializer=weni_dot_protobuf_dot_flows_dot_channel__pb2.ChannelCreateRequest.SerializeToString,
                response_deserializer=weni_dot_protobuf_dot_flows_dot_channel__pb2.Channel.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/weni.flows.channel.ChannelController/Retrieve',
                request_serializer=weni_dot_protobuf_dot_flows_dot_channel__pb2.ChannelRetrieveRequest.SerializeToString,
                response_deserializer=weni_dot_protobuf_dot_flows_dot_channel__pb2.Channel.FromString,
                )
        self.List = channel.unary_stream(
                '/weni.flows.channel.ChannelController/List',
                request_serializer=weni_dot_protobuf_dot_flows_dot_channel__pb2.ChannelListRequest.SerializeToString,
                response_deserializer=weni_dot_protobuf_dot_flows_dot_channel__pb2.Channel.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/weni.flows.channel.ChannelController/Destroy',
                request_serializer=weni_dot_protobuf_dot_flows_dot_channel__pb2.ChannelDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class ChannelControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChannelControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=weni_dot_protobuf_dot_flows_dot_channel__pb2.ChannelCreateRequest.FromString,
                    response_serializer=weni_dot_protobuf_dot_flows_dot_channel__pb2.Channel.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=weni_dot_protobuf_dot_flows_dot_channel__pb2.ChannelRetrieveRequest.FromString,
                    response_serializer=weni_dot_protobuf_dot_flows_dot_channel__pb2.Channel.SerializeToString,
            ),
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=weni_dot_protobuf_dot_flows_dot_channel__pb2.ChannelListRequest.FromString,
                    response_serializer=weni_dot_protobuf_dot_flows_dot_channel__pb2.Channel.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=weni_dot_protobuf_dot_flows_dot_channel__pb2.ChannelDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weni.flows.channel.ChannelController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChannelController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/weni.flows.channel.ChannelController/Create',
            weni_dot_protobuf_dot_flows_dot_channel__pb2.ChannelCreateRequest.SerializeToString,
            weni_dot_protobuf_dot_flows_dot_channel__pb2.Channel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/weni.flows.channel.ChannelController/Retrieve',
            weni_dot_protobuf_dot_flows_dot_channel__pb2.ChannelRetrieveRequest.SerializeToString,
            weni_dot_protobuf_dot_flows_dot_channel__pb2.Channel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/weni.flows.channel.ChannelController/List',
            weni_dot_protobuf_dot_flows_dot_channel__pb2.ChannelListRequest.SerializeToString,
            weni_dot_protobuf_dot_flows_dot_channel__pb2.Channel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/weni.flows.channel.ChannelController/Destroy',
            weni_dot_protobuf_dot_flows_dot_channel__pb2.ChannelDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class WeniWebChatControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/weni.flows.channel.WeniWebChatController/Create',
                request_serializer=weni_dot_protobuf_dot_flows_dot_channel__pb2.WeniWebChatCreateRequest.SerializeToString,
                response_deserializer=weni_dot_protobuf_dot_flows_dot_channel__pb2.WeniWebChat.FromString,
                )


class WeniWebChatControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeniWebChatControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=weni_dot_protobuf_dot_flows_dot_channel__pb2.WeniWebChatCreateRequest.FromString,
                    response_serializer=weni_dot_protobuf_dot_flows_dot_channel__pb2.WeniWebChat.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weni.flows.channel.WeniWebChatController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WeniWebChatController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/weni.flows.channel.WeniWebChatController/Create',
            weni_dot_protobuf_dot_flows_dot_channel__pb2.WeniWebChatCreateRequest.SerializeToString,
            weni_dot_protobuf_dot_flows_dot_channel__pb2.WeniWebChat.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
